### ISSUE TITLE
Crear handler: CreateClaimHandler (20 PUNTOS)

### ISSUE THREAD

**Issue by leandrofiore3** [leandrofiore3/PROYECTO-PRINCIPAL-Metodologia-de-Sistemas-I#9]
Crear handler: CreateClaimHandler (20 PUNTOS)

- El visitante debe tener un pin de 6 dígitos para validar que es él quien hace el reclamo

**Comment by PatricioPoncini** [comment]
Falta declarar algunos metodos en entidades
